from .router_achievements import router as achievements_router
from .router_admin import router as admin_router
from .router_answers import router as answers_router
from .router_auth import router as auth_router
from .router_categories import router as categories_router
from .router_game import router as game_router
from .router_guest import router as guest_router
from .router_lobby import router as lobby_router
from .router_media import router as media_router
from .router_questions import router as questions_router
from .router_quiz_results import router as quiz_results_router
from .router_quiz_session import router as quiz_session_router
from .router_quizzes import router as quizzes_router
from .router_users import router as users_router
