export const myQuizzes = [
  {
    id: 101,
    title: 'Мой квиз по программированию',
    category: 'Технологии',
    status: 'approved',
    participants: 45,
    rating: 4.5,
    createdAt: '10 апреля 2026',
  },
  {
    id: 102,
    title: 'История России',
    category: 'История',
    status: 'pending',
    participants: 0,
    rating: 0,
    createdAt: '11 апреля 2026',
  },
  {
    id: 103,
    title: 'Основы математики',
    category: 'Наука',
    status: 'rejected',
    participants: 0,
    rating: 0,
    createdAt: '9 апреля 2026',
  },
  {
    id: 104,
    title: 'JavaScript для начинающих',
    category: 'Технологии',
    status: 'approved',
    participants: 128,
    rating: 4.8,
    createdAt: '5 апреля 2026',
  },
  {
    id: 105,
    title: 'Викторина о космосе',
    category: 'Наука',
    status: 'approved',
    participants: 67,
    rating: 4.3,
    createdAt: '3 апреля 2026',
  },
  {
    id: 106,
    title: 'Великие художники',
    category: 'Искусство',
    status: 'pending',
    participants: 0,
    rating: 0,
    createdAt: '12 апреля 2026',
  },
  {
    id: 107,
    title: 'Мировые столицы',
    category: 'География',
    status: 'approved',
    participants: 234,
    rating: 4.9,
    createdAt: '1 апреля 2026',
  },
]
