export const myQuizzes = [
  {
    id: 101,
    title: 'Мой квиз по программированию',
    description: 'Тест на знание основ программирования и алгоритмов',
    category: 'Технологии',
    author: 'Алексей Иванов',
    status: 'approved',
    createdAt: '10 апреля 2026',
    questionCount: 15,
    difficulty: 'Средний',
    participants: 45,
    rating: 4.5,
  },
  {
    id: 102,
    title: 'История России',
    description:
      'Проверьте свои знания об истории России от древних времен до наших дней',
    category: 'История',
    author: 'Мария Петрова',
    status: 'pending',
    createdAt: '11 апреля 2026',
    questionCount: 20,
    difficulty: 'Сложный',
    participants: 0,
    rating: 0,
  },
  {
    id: 103,
    title: 'Основы математики',
    description: 'Базовые математические понятия и формулы',
    category: 'Наука',
    author: 'Сергей Сидоров',
    status: 'rejected',
    createdAt: '9 апреля 2026',
    questionCount: 10,
    difficulty: 'Легкий',
    participants: 0,
    rating: 0,
  },
  {
    id: 104,
    title: 'JavaScript для начинающих',
    description: 'Основы JavaScript: переменные, функции, условия, циклы',
    category: 'Технологии',
    author: 'Алексей Иванов',
    status: 'approved',
    createdAt: '5 апреля 2026',
    questionCount: 25,
    difficulty: 'Средний',
    participants: 128,
    rating: 4.8,
  },
  {
    id: 105,
    title: 'Викторина о космосе',
    description: 'Интересные факты о планетах, звездах и космических явлениях',
    category: 'Наука',
    author: 'Елена Космова',
    status: 'approved',
    createdAt: '3 апреля 2026',
    questionCount: 12,
    difficulty: 'Средний',
    participants: 67,
    rating: 4.3,
  },
  {
    id: 106,
    title: 'Великие художники',
    description:
      'Узнайте, насколько хорошо вы знаете известных художников и их картины',
    category: 'Искусство',
    author: 'Дмитрий Артёмов',
    status: 'pending',
    createdAt: '12 апреля 2026',
    questionCount: 18,
    difficulty: 'Средний',
    participants: 0,
    rating: 0,
  },
  {
    id: 107,
    title: 'Мировые столицы',
    description: 'Проверьте свои знания столиц стран мира',
    category: 'География',
    author: 'Анна Географическая',
    status: 'approved',
    createdAt: '1 апреля 2026',
    questionCount: 30,
    difficulty: 'Средний',
    participants: 234,
    rating: 4.9,
  },
  {
    id: 108,
    title: 'Английский язык: времена',
    description: 'Тест на знание времен в английском языке',
    category: 'Языки',
    author: 'Ольга Лингвист',
    status: 'pending',
    createdAt: '13 апреля 2026',
    questionCount: 20,
    difficulty: 'Сложный',
    participants: 0,
    rating: 0,
  },
  {
    id: 109,
    title: 'Классическая литература',
    description: 'Вспомните великие произведения русской и зарубежной классики',
    category: 'Литература',
    author: 'Иван Читатель',
    status: 'approved',
    createdAt: '28 марта 2026',
    questionCount: 15,
    difficulty: 'Сложный',
    participants: 89,
    rating: 4.6,
  },
  {
    id: 110,
    title: 'Спортивные достижения',
    description: 'Какие рекорды и события вы помните в мире спорта?',
    category: 'Спорт',
    author: 'Павел Спортивный',
    status: 'rejected',
    createdAt: '7 апреля 2026',
    questionCount: 10,
    difficulty: 'Легкий',
    participants: 0,
    rating: 0,
  },
]
