export const recentQuizzes = [
  {
    id: 1,
    title: "История Древнего мира",
    category: "История",
    score: 90,
    correctAnswers: 9,
    totalQuestions: 10,
    date: "28 февраля 2026",
    time: "15 мин",
  },
  {
    id: 2,
    title: "География мира",
    category: "География",
    score: 100,
    correctAnswers: 10,
    totalQuestions: 10,
    date: "27 февраля 2026",
    time: "10 мин",
  },
  {
    id: 3,
    title: "Кино и киноиндустрия",
    category: "Кино",
    score: 80,
    correctAnswers: 8,
    totalQuestions: 10,
    date: "26 февраля 2026",
    time: "15 мин",
  },
  {
    id: 4,
    title: "Музыкальная эрудиция",
    category: "Музыка",
    score: 70,
    correctAnswers: 7,
    totalQuestions: 10,
    date: "25 февраля 2026",
    time: "12 мин",
  },
  {
    id: 5,
    title: "Спортивный мир",
    category: "Спорт",
    score: 95,
    correctAnswers: 19,
    totalQuestions: 20,
    date: "24 февраля 2026",
    time: "18 мин",
  },
  {
    id: 6,
    title: "Технологии и IT",
    category: "Технологии",
    score: 85,
    correctAnswers: 17,
    totalQuestions: 20,
    date: "23 февраля 2026",
    time: "20 мин",
  },
  {
    id: 7,
    title: "Кулинарный квиз",
    category: "Еда",
    score: 100,
    correctAnswers: 10,
    totalQuestions: 10,
    date: "22 февраля 2026",
    time: "10 мин",
  },
  {
    id: 8,
    title: "Мир природы",
    category: "Природа",
    score: 75,
    correctAnswers: 15,
    totalQuestions: 20,
    date: "21 февраля 2026",
    time: "16 мин",
  },
  {
    id: 9,
    title: "Общие знания",
    category: "Общие",
    score: 88,
    correctAnswers: 22,
    totalQuestions: 25,
    date: "20 февраля 2026",
    time: "22 мин",
  },
  {
    id: 10,
    title: "Головоломки и логика",
    category: "Логика",
    score: 65,
    correctAnswers: 13,
    totalQuestions: 20,
    date: "19 февраля 2026",
    time: "25 мин",
  },
  {
    id: 11,
    title: "Популярная культура",
    category: "Культура",
    score: 92,
    correctAnswers: 23,
    totalQuestions: 25,
    date: "18 февраля 2026",
    time: "14 мин",
  },
  {
    id: 12,
    title: "Космос и астрономия",
    category: "Наука",
    score: 78,
    correctAnswers: 14,
    totalQuestions: 18,
    date: "17 февраля 2026",
    time: "19 мин",
  },
];
